version: '3.8'

services:
    mysql:
        image: mysql:8.0
        container_name: mysql_local_4408
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword  # Root password for administration
            MYSQL_USER: myuser  # ✅ Single user for all databases
            MYSQL_PASSWORD: mypassword  # ✅ Shared password
        ports:
            - "4408:3306"
        volumes:
            - mysql_data_jlr_db_4408:/var/lib/mysql
            - ./mysql-config/my.cnf:/etc/mysql/my.cnf  # ✅ Mount custom MySQL config

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_4409
        restart: always
        environment:
            PMA_HOST: mysql  # ✅ MySQL service name in Docker
            PMA_PORT: 3306
        ports:
            - "4409:80"  # ✅ phpMyAdmin accessible on http://localhost:4409
        depends_on:
            - mysql  # ✅ Ensure MySQL starts before phpMyAdmin

volumes:
    mysql_data_jlr_db_4408:
